#########################################################
# Specify the name of the target executable

TARGETS:=frs_april2019

#########################################################
# Include common Makefile

include ../makefile_common.mk
