#########################################################
# Specify the name of the target executable

TARGETS:=swasa

#########################################################
# Include common Makefile

include ../makefile_common.mk
